apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-sakila
  labels:
    app: postgres-sakila
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-sakila
  template:
    metadata:
      labels:
        app: postgres-sakila
    spec:
      containers:
      - name: postgres-sakila
        image: public.ecr.aws/m9h2b5e7/postgres-sakila:270723
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "sakila"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-playground
  labels:
    app.kubernetes.io/name: security-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: security-playground
  template:
    metadata:
      labels:
        app.kubernetes.io/name: security-playground
    spec:
      hostPID: true
      containers:
        - name: security-playground
          image: public.ecr.aws/m9h2b5e7/security-playground:270723
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: security-playground
  labels:
    app.kubernetes.io/name: security-playground
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30000
  selector:
    app.kubernetes.io/name: security-playground